spring:
  liquibase:
    enabled: true
  application:
    name: beer_pet_project
  datasource:
    url: jdbc:postgresql://localhost:5432/Beer_Database
    username: postgres
    password: Dataparole

com:
  group:
    project:
        secret: 8b8bc66f6b3525d94e39f4927e518f75c7769409388c4e62868fd6bc3e781220f141edc1
        baseTokenExpiresIn: 900
        refreshTokenExpiresIn: 86400

jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
     hibernate:
       format_sql: true
       dialect:
        org:
        hibernate:
            dialect:PostgreSQLDialect


